#!/usr/bin/env python3
"""Review Council — GitHub Action entry point.

Fetches the PR diff, runs the 3-stage council, and posts the
consolidated review as a PR comment.

Environment variables (set by workflow.yml):
  PR_NUMBER              — pull request number
  PR_TITLE               — pull request title
  PR_BODY                — pull request description body
  REPO                   — "owner/repo" (e.g. "scholete/pulse")
  SHA                    — head commit SHA for status checks
  GITHUB_TOKEN           — auto-generated by Actions workflow
  NEURALWATT_API_KEY     — (set in repo secrets)
  DEEPSEEK_API_KEY       — (set in repo secrets)
"""

import os
import sys
import json
import traceback

# Ensure the repo root is on sys.path so relative backend imports work.
_REPO_ROOT = os.path.dirname(os.path.abspath(__file__))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

# ── Import backend modules ─────────────────────────────────────────

os.environ.setdefault("DATA_DIR", "/tmp/review-council-data")

from backend.config import COUNCIL_MODELS, CHAIRMAN_MODEL
from backend.llm_client import query_model, query_models_parallel
from backend.council import (
    stage1_collect_reviews,
    stage2_collect_rankings,
    stage3_synthesize_final,
    calculate_aggregate_rankings,
)
from backend.github_integration import (
    fetch_pr_diff,
    post_pr_review,
    set_commit_status,
    list_open_prs,
)

# ── Helpers ─────────────────────────────────────────────────────────


def _env(key: str, default: str = "") -> str:
    return os.environ.get(key, default)


def _die(msg: str):
    print(f"❌ {msg}", file=sys.stderr)
    sys.exit(1)


# ── Main ────────────────────────────────────────────────────────────


async def main():
    pr_number = _env("PR_NUMBER")
    pr_title = _env("PR_TITLE")
    pr_body = _env("PR_BODY")
    repo_full = _env("REPO")
    sha = _env("SHA")
    token = _env("GITHUB_TOKEN")
    neuralwatt_key = _env("NEURALWATT_API_KEY")
    deepseek_key = _env("DEEPSEEK_API_KEY")

    if not repo_full or not pr_number:
        # Fallback: review ALL open PRs across monitored repos
        print("ℹ️  No PR_NUMBER / REPO — checking all monitored repos for open PRs...")
        open_prs = await list_open_prs()
        if not open_prs:
            print("✅ No open PRs to review.")
            return
        for pr in open_prs:
            await _review_single_pr(
                owner=pr["owner"],
                repo=pr["repo"],
                pr_number=pr["number"],
                pr_title=pr.get("title", ""),
                token=token,
            )
        return

    if "/" not in repo_full:
        _die(f"REPO must be 'owner/repo', got: {repo_full}")
    owner, repo_name = repo_full.split("/", 1)

    ok = await _review_single_pr(
        owner=owner,
        repo=repo_name,
        pr_number=int(pr_number),
        pr_title=pr_title,
        pr_description=pr_body,
        sha=sha,
        token=token,
    )
    if not ok:
        sys.exit(1)


async def _review_single_pr(
    *,
    owner: str,
    repo: str,
    pr_number: int,
    pr_title: str = "",
    pr_description: str = "",
    sha: str = "",
    token: str = "",
) -> bool:
    """Run the full 3-stage review on a single PR.

    Returns ``True`` on success, ``False`` on failure.
    """
    print(f"\n{'='*60}")
    print(f"🚀 Reviewing: {owner}/{repo} #{pr_number} — {pr_title}")
    print(f"{'='*60}")

    # ── 1. Fetch diff ──────────────────────────────────────────
    print("📥 Fetching diff...")
    pr_data = await fetch_pr_diff(owner, repo, pr_number)
    if pr_data is None:
        print(f"❌ Failed to fetch PR #{pr_number} from {owner}/{repo}")
        if sha:
            await set_commit_status(owner, repo, sha, state="failure",
                                    description="Review Council: unable to fetch PR diff (check token permissions)")
        return False

    diff_text = pr_data["diff_text"]
    sha = sha or pr_data.get("sha", "")
    title = pr_title or pr_data.get("title", "")
    description = pr_description or pr_data.get("description", "")

    # ── 2. Set pending status ──────────────────────────────────
    if sha and token:
        await set_commit_status(
            owner, repo, sha,
            state="pending",
            description="Review Council is analysing this PR...",
        )

    # ── 3. Stage 1 ─────────────────────────────────────────────
    print("🔍 Stage 1: Individual reviews...")
    stage1 = await stage1_collect_reviews(
        diff_text,
        repo=repo,
        pr_title=title,
        pr_description=description,
    )
    if not stage1:
        print("❌ All models failed during Stage 1.")
        _post_failure_comment(owner, repo, pr_number, "All models failed to respond.")
        if sha:
            await set_commit_status(owner, repo, sha, state="failure",
                                    description="Review Council: models unavailable")
        return False

    print(f"   ✓ {len(stage1)} review(s) collected")

    # ── 4. Stage 2 ─────────────────────────────────────────────
    print("📊 Stage 2: Meta-review (evaluating reviews)...")
    stage2, label_to_model = await stage2_collect_rankings(
        diff_text, stage1, repo=repo, pr_title=title,
    )
    aggregate = calculate_aggregate_rankings(stage2, label_to_model)
    print(f"   ✓ {len(stage2)} evaluation(s) collected")

    # ── 5. Stage 3 ─────────────────────────────────────────────
    print("🎯 Stage 3: Chairman synthesis...")
    stage3 = await stage3_synthesize_final(
        diff_text, stage1, stage2,
        repo=repo, pr_title=title,
    )

    # ── 6. Build review body ───────────────────────────────────
    verdict = "✅ Approved"
    if stage3.get("response") is None:
        verdict = "❌ Error — no synthesis produced"
    else:
        # Search the full response (not just first 500 chars) for verdict markers
        lower = stage3["response"].lower()
        # Check for denial/changes markers first — Approve is the default
        if "❌" in stage3["response"] and "deny" in lower:
            verdict = "❌ Denied"
        elif "⚠️" in stage3["response"] and "changes" in lower:
            verdict = "⚠️ Changes Requested"
        elif "deny" in lower:
            verdict = "❌ Denied"
        elif "changes requested" in lower:
            verdict = "⚠️ Changes Requested"

    review_body = f"""# Review Council — {owner}/{repo} #{pr_number}

**Verdict: {verdict}**

---

{stage3.get('response', '*No synthesis produced*')}

---

<sub>Reviewed by {', '.join(f'{c["provider"]}/{c["model"]}' for c in COUNCIL_MODELS)} · Chairman: {CHAIRMAN_MODEL["provider"]}/{CHAIRMAN_MODEL["model"]}</sub>
"""
    # ── 7. Post review to PR ───────────────────────────────────
    print("📤 Posting review to PR...")
    posted = await post_pr_review(owner, repo, pr_number, review_body)
    if posted:
        print(f"   ✓ Review posted to {owner}/{repo}#{pr_number}")
    else:
        print(f"   ⚠️  Failed to post review")

    # ── 8. Update commit status ────────────────────────────────
    if sha:
        if stage3.get("response") is None:
            state = "failure"
            desc = "Review Council: synthesis failed"
        else:
            # Read the verdict from the review body itself
            lower = review_body.lower()
            if "✅ approved" in lower:
                state = "success"
                desc = "Review Council: approved"
            elif "❌ denied" in lower:
                state = "failure"
                desc = "Review Council: denied"
            elif "⚠️ changes requested" in lower:
                state = "failure"
                desc = "Review Council: changes requested"
            else:
                # Fallback — search the response text for keywords
                resp_lower = (stage3.get("response") or "").lower()
                if "approve" in resp_lower[:300]:
                    state = "success"
                    desc = "Review Council: approved"
                else:
                    state = "failure"
                    desc = "Review Council: changes requested"
        await set_commit_status(owner, repo, sha, state=state, description=desc)
        print(f"   ✓ Commit status set: {state}")

    print(f"✅ Done — {owner}/{repo} #{pr_number}\n")
    return True


def _post_failure_comment(owner: str, repo: str, pr_number: int, message: str):
    """Synchronous fallback — imports httpx directly."""
    import httpx

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return

    body = f"# Review Council\n\n⚠️ **Review failed**\n\n{message}\n"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "review-council/1.0",
    }
    with httpx.Client() as client:
        client.post(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{pr_number}/comments",
            headers=headers,
            json={"body": body},
        )


# ── Entry ───────────────────────────────────────────────────────────

if __name__ == "__main__":
    import asyncio

    try:
        asyncio.run(main())
    except Exception:
        print("❌ Unhandled error:", file=sys.stderr)
        traceback.print_exc()
        sys.exit(1)
